server:
  port: 9010

spring:
  application:
    name: feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.kuraki.service.HelloService: debug
