server:
  port: 8090
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloudstudy
    username: root
    password: 1234

mybatis:
  type-aliases-package: com.kuraki.bean
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: com.kuraki.mapper
  identity: mysql


